/**
 * ChartSpec → runnable, heavily-commented Python (matplotlib + pandas).
 *
 * Free, no watermark. Padding, spacing, and text-label knobs are named
 * variables at the TOP so users can fine-tune without hunting through the
 * plot call. Each form maps to its closest matplotlib call; a form without
 * a faithful mapping emits the nearest call plus a comment (honest degrade).
 */
import type { ChartSpec } from '@postr/shared';
import { rowsForMode, columnLiteral, type DataMode } from './data';

function dataFramePy(spec: ChartSpec, mode: DataMode): string {
  const rows = rowsForMode(spec, mode);
  const cols = spec.data.columns.map((col, c) => {
    const values = rows.map((r) => r[c] ?? null);
    return `    ${pyStr(col.name)}: [${columnLiteral(values, col.kind, 'py')}]`;
  });
  return `df = pd.DataFrame({\n${cols.join(',\n')},\n})`;
}

/** form → matplotlib body (uses `ax`) + optional approximation note. */
function plotPy(spec: ChartSpec): { body: string[]; note?: string } {
  const x = spec.encoding.x ?? spec.data.columns[0]?.name ?? 'x';
  const y = spec.encoding.y ?? spec.data.columns[1]?.name ?? 'y';
  const series = spec.encoding.series;
  const gx = pyStr(x);
  const gy = pyStr(y);
  switch (spec.form) {
    case 'bar':
      return { body: [`ax.bar(df[${gx}], df[${gy}], width=bar_width, color="#4c78a8")`] };
    case 'bar-grouped':
      return {
        body: [
          '# Grouped bars: one offset series per group.',
          `for i, (name, grp) in enumerate(df.groupby(${pyStr(series ?? '')})):`,
          `    ax.bar([xi + i * group_gap for xi in range(len(grp))], grp[${gy}], width=bar_width, label=str(name))`,
          'ax.legend()',
        ],
      };
    case 'bar-stacked':
      return {
        body: [
          '# Stacked bars: cumulative bottoms per series.',
          'bottom = None',
          `for name, grp in df.groupby(${pyStr(series ?? '')}):`,
          `    ax.bar(grp[${gx}], grp[${gy}], width=bar_width, bottom=bottom, label=str(name))`,
          `    bottom = grp[${gy}].values if bottom is None else bottom + grp[${gy}].values`,
          'ax.legend()',
        ],
      };
    case 'bar-diverging':
      return {
        body: [`ax.barh(df[${gx}], df[${gy}], height=bar_width, color="#4c78a8")`],
        note: 'diverging bars: values are expected to be signed (negative = left of zero).',
      };
    case 'line':
      return { body: [`ax.plot(df[${gx}], df[${gy}], linewidth=line_width)`] };
    case 'area':
      return { body: [`ax.fill_between(df[${gx}], df[${gy}], alpha=0.8)`] };
    case 'scatter':
      return { body: [`ax.scatter(df[${gx}], df[${gy}], s=point_size ** 2)`] };
    case 'histogram':
      return { body: [`ax.hist(df[${gx}], bins=30, color="#4c78a8")`], note: 'histogram: bin count is a starting point — tune `bins`.' };
    case 'box':
      return { body: [`ax.boxplot([df[${gy}].dropna()], labels=[${gy}])`], note: 'boxplot: shown for a single series; group by a category for multiple boxes.' };
    case 'heatmap':
      return {
        body: [
          `pivot = df.pivot(index=${gy}, columns=${gx}, values=${pyStr(spec.encoding.value ?? y)})`,
          'im = ax.imshow(pivot, aspect="auto")',
          'fig.colorbar(im, ax=ax)',
        ],
        note: 'heatmap: needs x, y, and a value column.',
      };
    case 'dumbbell':
      return {
        body: [
          '# Dumbbell approximated with paired points + connecting lines.',
          `for _, row in df.iterrows():`,
          `    ax.plot([row[${gy}], row[${gy}]], [row[${gx}], row[${gx}]])`,
          `ax.scatter(df[${gy}], df[${gx}], s=point_size ** 2)`,
        ],
        note: 'dumbbell: matplotlib has no native dumbbell; this pairs points with a line.',
      };
    default:
      return { body: [`ax.scatter(df[${gx}], df[${gy}])`], note: `unmapped form "${spec.form}" — using points as a fallback.` };
  }
}

export function chartSpecToPython(spec: ChartSpec, mode: DataMode = 'sample'): string {
  const title = spec.title ?? '';
  const xLabel = spec.xLabel ?? spec.encoding.x ?? '';
  const yLabel = spec.yLabel ?? spec.encoding.y ?? '';
  const { body, note } = plotPy(spec);
  const modeNote =
    mode === 'sample'
      ? '# NOTE: the data below is SAMPLE data with the same shape as yours.\n# Replace it with your own — or uncomment the CSV loader below.'
      : '# The data below is your data, embedded inline.\n# To use a file instead, uncomment the CSV loader below.';

  return [
    '# Generated by postr.sh — free to use and edit, no attribution required.',
    '# Requires: pip install matplotlib pandas',
    'import matplotlib.pyplot as plt',
    'import pandas as pd',
    '',
    '# ─── Fine-tune here ─────────────────────────────────────────────',
    '# Padding around the plot as fractions of the figure (0–1):',
    'pad_left, pad_right = 0.12, 0.96',
    'pad_bottom, pad_top = 0.12, 0.90',
    '# Spacing / sizing of the marks:',
    'bar_width  = 0.8    # width of bars',
    'group_gap  = 0.9    # offset between grouped bars',
    'line_width = 1.5    # thickness of lines',
    'point_size = 5      # radius-ish of scatter points',
    '# Text labels:',
    `plot_title = ${pyStr(title)}`,
    `x_label    = ${pyStr(xLabel)}`,
    `y_label    = ${pyStr(yLabel)}`,
    '# Text sizes (points):',
    'title_size, axis_title_size, axis_text_size = 16, 13, 11',
    '# Final figure size in inches (tune for your print size):',
    'fig_w, fig_h, dpi = 8, 5.6, 300',
    '# ────────────────────────────────────────────────────────────────',
    '',
    modeNote,
    dataFramePy(spec, mode),
    '',
    '# To load your own CSV instead of the inline data above, uncomment:',
    '# df = pd.read_csv("your-data.csv")',
    '',
    ...(note ? [`# NOTE: ${note}`, ''] : []),
    'fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=dpi)',
    ...body,
    '',
    'ax.set_title(plot_title, fontsize=title_size, fontweight="bold")',
    'ax.set_xlabel(x_label, fontsize=axis_title_size)',
    'ax.set_ylabel(y_label, fontsize=axis_title_size)',
    'ax.tick_params(labelsize=axis_text_size)',
    'fig.subplots_adjust(left=pad_left, right=pad_right, bottom=pad_bottom, top=pad_top)',
    '',
    'plt.show()',
    '# Save at your final figure size:',
    '# fig.savefig("figure.png", dpi=dpi, bbox_inches="tight")',
    '',
  ].join('\n');
}

/** Python string literal. */
function pyStr(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
