/**
 * ChartSpec → runnable, heavily-commented R (ggplot2).
 *
 * Free, no watermark. The point is that a user can (a) link their own data
 * and (b) fine-tune padding, spacing, and text labels — so those knobs are
 * named variables at the TOP, not buried in the plot call. Every form maps
 * to its closest ggplot geom; a form without a faithful 1:1 mapping emits
 * the nearest geom plus a comment flagging the approximation (honest
 * degrade), never a silently-wrong chart.
 */
import type { ChartSpec } from '@postr/shared';
import { rowsForMode, columnLiteral, type DataMode } from './data';

function dataFrameR(spec: ChartSpec, mode: DataMode): string {
  const rows = rowsForMode(spec, mode);
  const cols = spec.data.columns.map((col, c) => {
    const values = rows.map((r) => r[c] ?? null);
    return `  \`${col.name}\` = c(${columnLiteral(values, col.kind, 'r')})`;
  });
  return `df <- data.frame(\n${cols.join(',\n')},\n  check.names = FALSE,\n  stringsAsFactors = FALSE\n)`;
}

/** form → ggplot geom + a note when it isn't a faithful 1:1 mapping. */
function geomR(spec: ChartSpec): { geom: string; note?: string } {
  const x = spec.encoding.x ?? spec.data.columns[0]?.name ?? 'x';
  const y = spec.encoding.y ?? spec.data.columns[1]?.name ?? 'y';
  const series = spec.encoding.series;
  const fill = series ? `, fill = \`${series}\`` : '';
  const color = series ? `, colour = \`${series}\`` : '';
  switch (spec.form) {
    case 'bar':
      return { geom: `  geom_col(aes(x = \`${x}\`, y = \`${y}\`), width = bar_width, fill = "#4c78a8")` };
    case 'bar-grouped':
      return { geom: `  geom_col(aes(x = \`${x}\`, y = \`${y}\`${fill}), width = bar_width, position = position_dodge(width = group_gap))` };
    case 'bar-stacked':
      return { geom: `  geom_col(aes(x = \`${x}\`, y = \`${y}\`${fill}), width = bar_width, position = "stack")` };
    case 'bar-diverging':
      return {
        geom: `  geom_col(aes(x = \`${x}\`, y = \`${y}\`${fill}), width = bar_width) +\n  coord_flip()`,
        note: 'diverging bars: values are expected to be signed (negative = left of zero).',
      };
    case 'line':
      return { geom: `  geom_line(aes(x = \`${x}\`, y = \`${y}\`${color}), linewidth = line_width)` };
    case 'area':
      return { geom: `  geom_area(aes(x = \`${x}\`, y = \`${y}\`${fill}), alpha = 0.8)` };
    case 'scatter':
      return { geom: `  geom_point(aes(x = \`${x}\`, y = \`${y}\`${color}), size = point_size)` };
    case 'histogram':
      return { geom: `  geom_histogram(aes(x = \`${x}\`), bins = 30, fill = "#4c78a8")`, note: 'histogram: bin count is a starting point — tune `bins`.' };
    case 'box':
      return { geom: `  geom_boxplot(aes(x = \`${x}\`, y = \`${y}\`${fill}))` };
    case 'heatmap':
      return { geom: `  geom_tile(aes(x = \`${x}\`, y = \`${y}\`, fill = \`${spec.encoding.value ?? y}\`))`, note: 'heatmap: needs x, y, and a value column for the fill.' };
    case 'dumbbell':
      return {
        geom: `  geom_line(aes(x = \`${x}\`, y = \`${y}\`, group = \`${x}\`)) +\n  geom_point(aes(x = \`${x}\`, y = \`${y}\`${color}), size = point_size)`,
        note: 'dumbbell: approximated with paired points + connecting line; for a true dumbbell see the ggalt package (geom_dumbbell).',
      };
    default:
      return { geom: `  geom_point(aes(x = \`${x}\`, y = \`${y}\`))`, note: `unmapped form "${spec.form}" — using points as a fallback.` };
  }
}

export function chartSpecToR(spec: ChartSpec, mode: DataMode = 'sample'): string {
  const title = spec.title ?? '';
  const xLabel = spec.xLabel ?? spec.encoding.x ?? '';
  const yLabel = spec.yLabel ?? spec.encoding.y ?? '';
  const { geom, note } = geomR(spec);
  const modeNote =
    mode === 'sample'
      ? '# NOTE: the data below is SAMPLE data with the same shape as yours.\n# Replace it with your own — or uncomment the CSV loader below.'
      : '# The data below is your data, embedded inline.\n# To use a file instead, uncomment the CSV loader below.';

  return [
    '# Generated by postr.sh — free to use and edit, no attribution required.',
    '# Requires: install.packages("ggplot2")',
    'library(ggplot2)',
    '',
    '# ─── Fine-tune here ─────────────────────────────────────────────',
    '# Padding around the whole plot (top, right, bottom, left), in points:',
    'plot_padding <- margin(12, 12, 12, 12)',
    '# Spacing / sizing of the marks:',
    'bar_width  <- 0.8   # 0–1; width of bars',
    'group_gap  <- 0.9   # dodge width between grouped bars',
    'line_width <- 1.0   # thickness of lines',
    'point_size <- 2.5   # size of scatter/dumbbell points',
    '# Text labels:',
    `plot_title <- ${rStr(title)}`,
    `x_label    <- ${rStr(xLabel)}`,
    `y_label    <- ${rStr(yLabel)}`,
    '# Text sizes (points):',
    'title_size <- 16',
    'axis_title_size <- 13',
    'axis_text_size  <- 11',
    '# ────────────────────────────────────────────────────────────────',
    '',
    modeNote,
    dataFrameR(spec, mode),
    '',
    '# To load your own CSV instead of the inline data above, uncomment:',
    '# df <- read.csv("your-data.csv", check.names = FALSE)',
    '',
    ...(note ? [`# NOTE: ${note}`, ''] : []),
    'p <- ggplot(df) +',
    geom + ' +',
    '  labs(title = plot_title, x = x_label, y = y_label) +',
    '  theme_minimal(base_size = axis_text_size) +',
    '  theme(',
    '    plot.margin      = plot_padding,',
    '    plot.title       = element_text(size = title_size, face = "bold"),',
    '    axis.title       = element_text(size = axis_title_size),',
    '    axis.text        = element_text(size = axis_text_size),',
    '    panel.grid.minor = element_blank()',
    '  )',
    '',
    'print(p)',
    '# Save at your final figure size (tune width/height/dpi):',
    '# ggsave("figure.png", p, width = 8, height = 5.6, dpi = 300)',
    '',
  ].join('\n');
}

/** R string literal (quotes, escapes). */
function rStr(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
