/**
 * references.bib generation for the LaTeX export bundle.
 *
 * Field-based references become @article entries; references the
 * user pasted pre-formatted (rawText) become @misc entries carrying
 * the text in `note` so nothing is lost. The .tex file renders the
 * reference list as literal text (matching the poster exactly), so
 * the .bib is a convenience for users who keep editing in LaTeX —
 * both representations ship.
 */
import type { Reference } from '@postr/shared';
import {
  acknowledgementBibEntry,
  shouldAttribute,
  type AttributionOptions,
} from '../attribution';
import { escapeLatex } from './escape';

/** Citation key: first author's last name + year, deduped. */
function citationKey(ref: Reference, index: number, used: Set<string>): string {
  const lastName = (ref.authors[0] ?? '').split(',')[0]?.trim() ?? '';
  const base =
    (lastName.replace(/[^A-Za-z]/g, '').toLowerCase() || `ref${index + 1}`) +
    (ref.year?.replace(/[^0-9]/g, '') ?? '');
  let key = base;
  let suffix = 98; // 'b' — first duplicate gets "smith2026b"
  while (used.has(key)) {
    key = base + String.fromCharCode(suffix);
    suffix += 1;
  }
  used.add(key);
  return key;
}

function bibField(name: string, value: string | undefined): string | null {
  const v = value?.trim();
  if (!v) return null;
  return `  ${name} = {${escapeLatex(v)}}`;
}

function formatEntry(ref: Reference, index: number, used: Set<string>): string {
  const key = citationKey(ref, index, used);
  const raw = ref.rawText?.trim();
  if (raw) {
    const fields = [bibField('note', raw), bibField('year', ref.year)]
      .filter((f): f is string => f !== null)
      .join(',\n');
    return `@misc{${key},\n${fields},\n}`;
  }
  const fields = [
    bibField('author', ref.authors.join(' and ')),
    bibField('title', ref.title),
    bibField('journal', ref.journal),
    bibField('year', ref.year),
    bibField('doi', ref.doi),
  ]
    .filter((f): f is string => f !== null)
    .join(',\n');
  return `@article{${key},\n${fields},\n}`;
}

/**
 * Render the full references.bib content.
 *
 * The Postr credit ships as a real `@misc{postr,...}` entry appended
 * last — not merely as the header comment, which `\bibliography`
 * cannot cite. Because the .bib exists so users can keep editing in
 * LaTeX, a citable entry is the only form of the credit that survives
 * into their recompiled document.
 *
 * A poster with NO references still emits the bib when the credit is
 * active: a one-entry .bib is valid and keeps `\bibliography` working
 * for a user who adds citations later in LaTeX.
 */
export function referencesToBib(
  references: readonly Reference[],
  options: AttributionOptions = {},
): string {
  const used = new Set<string>();
  const entries = references.map((r, i) => formatEntry(r, i, used));
  const ack = shouldAttribute(options) ? acknowledgementBibEntry() : null;
  if (ack) entries.push(ack);
  if (entries.length === 0) return '';
  return `% Generated by Postr (postr.sh)\n% Every poster reference, ready for \\bibliography.\n\n${entries.join('\n\n')}\n`;
}
