/**
 * Generated Supabase database types.
 *
 * This file is regenerated by `npm run db:types` (which calls
 * `supabase gen types typescript --local > …`). Do NOT edit by hand.
 *
 * The placeholder type below exists so downstream code can import
 * `Database` before `supabase start` has been run for the first time.
 * Run `npm run db:start && npm run db:types` to populate it.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Placeholder until `supabase gen types typescript --local` runs.
// Once Docker + Supabase are up locally, replace this file by running:
//   npm run db:types
export type Database = Record<string, unknown>;
